name: coord_convert
description: Small library to convert coordinates between different coordinate systems.
version: 0.1.0
homepage: https://github.com/mattermoran/coord_convert

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
